<?php
use Phalcon\Tag;
use TableSort\Sort;
$controller = $this->dispatcher->getControllerName();
$this->tag->setTitle("Записи");
function displayField($field){
  return $field === null ? '<kbd>(Пусто)</kbd>' : $field;
}
?>
<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>Записи</h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <?= Tag::linkTo(['/admin/' . $controller . '/create', 'Добавить запись', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>
      
      <div class="table-responsive">
        <form action="/admin/<?= $controller ?>/index" method="GET">
        <button type="submit" class="btn btn-primary d-none">Поиск</button>
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('id'), $model->getLabels('id') . Sort::sortIcon('id')]) ?>
                <input class="form-control" type="number" name="id" min="0" value="<?= $this->request->getQuery("id", "int") ?>">  
              </th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('name'), $model->getLabels('name') . ' ' . Sort::sortIcon('name')]) ?>
                <input class="form-control" type="text" name="name" value="<?= $this->request->getQuery("name") ?>">
              </th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('active'), $model->getLabels('active') . ' ' . Sort::sortIcon('active')]) ?>
                <input class="form-control" type="number" name="active" min="0" value="<?= $this->request->getQuery("active") ?>">
              </th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('user_id'), $model->getLabels('user_id') . ' ' . Sort::sortIcon('user_id')]) ?>
                  <input class="form-control" type="number" name="user_id" min="0" value="<?= $this->request->getQuery("user_id") ?>">
              </th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('category_id'), $model->getLabels('category_id') . ' ' . Sort::sortIcon('category_id')]) ?>
                  <input class="form-control" type="number" name="category_id" min="0" value="<?= $this->request->getQuery("category_id") ?>">
              </th>
              <th>Действия</th>
            </tr>
          </thead>
          <tbody>
            <?php $i = 0; foreach ($page->items as $key): ?>
              <tr>
                <td><?= ++$i; ?></td>
                <td><?= $key->id ?></td>
                <td><?= displayField($key->name) ?></td>
                <td><?= displayField($key->active) ?></td>
                <td><?= displayField($key->user_id) ?></td>
                <td><?= displayField($key->category_id) ?></td>
                <td class="btn-group mr-2">
                    <?= Tag::linkTo(['admin/' . $controller . '/view/' . $key->id, '<i class="far fa-eye"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                    <?= Tag::linkTo(['admin/' . $controller . '/edit/' . $key->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                    <?= Tag::linkTo(['admin/' . $controller . '/delete/' . $key->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
        </form>


      <nav aria-label="Page navigation example">
          <?php $page->items; ?>
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index"><i class="fas fa-angle-double-left"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->before; ?>"><i class="fas fa-angle-left"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->next; ?>"><i class="fas fa-angle-right"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->last; ?>"><i class="fas fa-angle-double-right"></i></a></li>
        </ul>
         <?php echo 'Страница ', $page->current, ' из ', $page->total_pages; ?>
      </nav>

      </div>