<?php
use Phalcon\Tag;

$this->breadcrumbs->setLastNotLinked(true);
$this->breadcrumbs->setSeparator('');
$this->breadcrumbs->setTemplate(
    '<li class="breadcrumb-item"><a href="{{link}}">{{icon}}{{label}}</a></li>', // linked
    '<li class="breadcrumb-item active">{{icon}}{{label}}</li>',         // not linked
    '<i class="fas fa-home"></i>'                    // first icon
);

$menus = [
    [
        'route' => 'admin/index/index',
        'name' => '<span data-feather="home"></span>Главная <span class="sr-only">(current)</span>',
        'controller' => 'index',
    ],
    [
        'route' => 'admin/users/index',
        'name' => '<span data-feather="users"></span>Пользователи <span class="sr-only">(current)</span>',
        'controller' => 'users',
    ],
    [
        'route' => 'admin/posts/index',
        'name' => '<span data-feather="layers"></span>Записи <span class="sr-only">(current)</span>',
        'controller' => 'posts',
    ],
    [
        'route' => 'admin/categories/index',
        'name' => '<span data-feather="file"></span>Категории <span class="sr-only">(current)</span>',
        'controller' => 'categories',
    ],
    [
        'route' => 'admin/comments/index',
        'name' => '<span data-feather="layers"></span>Комментарии <span class="sr-only">(current)</span>',
        'controller' => 'comments',
    ],
    [
        'route' => 'admin/pages/index',
        'name' => '<span data-feather="file-text"></span>Страницы <span class="sr-only">(current)</span>',
        'controller' => 'pages',
    ],
    [
        'route' => 'admin/menu/index',
        'name' => '<span data-feather="file-text"></span>Меню <span class="sr-only">(current)</span>',
        'controller' => 'menu',
    ],
    [
        'route' => 'admin/galleries/index',
        'name' => '<span data-feather="layers"></span>Галереи <span class="sr-only">(current)</span>',
        'controller' => 'galleries',
    ],
];
?>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <?= Tag::linkTo(['admin/session/logout', '<i class="fas fa-sign-out-alt"></i> Выйти', 'class' => 'nav-link']) ?>
    </li>
  </ul>
</nav>
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
        <?php foreach ($menus as $key => $value): ?>
            <li class="nav-item">
                <?php 
                $this->dispatcher->getControllerName() === $value['controller'] ? $menuLinkClass = 'nav-link active' : $menuLinkClass = 'nav-link';
                ?>
                <?= Tag::linkTo([$value['route'], $value['name'], 'class' => $menuLinkClass]) ?>
            </li>
        <?php endforeach; ?>

          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <?php if($this->dispatcher->getControllerName() !== 'index'): ?>
        <ol class="breadcrumb mb-0 mt-3 mb-3">
            <?php $this->breadcrumbs->output(); ?>
        </ol>
        <?php endif; ?>
        <?php $this->flash->output() ?>
        <?php $this->flashSession->output() ?>
        <?= $this->getContent(); ?>
    </main>
  </div>
</div>
