<?php
use Phalcon\Tag;
use App\Models\Images;
?>
<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2><?= $crudTitle ?></h2>
</div>

<form method="POST" enctype="multipart/form-data" action="<?= !$model->edit ? '/admin/' . $this->dispatcher->getControllerName() . '/create' : '/admin/' . $this->dispatcher->getControllerName() . '/edit/' . $model->id ?>">

	<div class="form-group">
 		<?= $model->label('logo'); ?>
    	<div class="input-group input-group-btn-del">
	    	<span class="input-group-btn">
		    	<span class="btn btn-default btn-file btn-primary">Загрузить
		    		<?= Tag::fileField(['logo', 'class' => 'form-control', 'id' => 'imgInp']); ?>
		    	</span>
	    	</span>
	    	<input type="text" class="form-control clear" readonly="" <?php if($model->logo): ?>value="<?= $model->logo ?>"<?php endif; ?>>
	    	<?php if($model->logo): ?>
	    	<span class="btn btn-primary btn-del" data-url="/admin/<?= $this->dispatcher->getControllerName() ?>/removeimage" data-id="<?= $model->id ?>">Удалить</span>
	    	<?php endif; ?>
    	</div>
    	<img 
    	id="img-upload" 
    	<?php if($model->logo): ?>
    	src="<?= Images::render($model->imgUploadDir . $model->logo); ?>"
    	<?php endif; ?>  />
	</div>

 	<div class="form-group">
 		<?= $model->label('name'); ?>
    	<?= Tag::textField(['name', 'maxlength' => 30, 'class' => 'form-control', 'placeholder' => 'Введите название', 'required' => 'required']); ?>
	</div>

	<div class="form-group">
 		<?= $model->label('alias'); ?>
    	<?= Tag::textField(['alias', 'maxlength' => 30, 'class' => 'form-control', 'placeholder' => 'Введите адрес']); ?>
	</div>

	<div class="form-group">
		<?= $model->label('parent_id'); ?>
		<?= Tag::select(['parent_id', $categories,
			"using" => [
    	        "id",
    	        "name"
    	    ],
    	    "useEmpty"   => true,
    	    "emptyText"  => "Выберите родительскую категорию",
    	    "emptyValue" => "",
    	    'class' => 'form-control'
    	]); ?>
	</div>

    <div class="form-group">
		<?= $model->label('active'); ?>
		<?= Tag::select(['active', [0 => 'Нет', 1 => 'Да'],
    	    'class' => 'form-control'
    	]); ?>
    </div>

	<button type="submit" class="btn btn-primary">Сохранить</button>

</form>