<?php
use Phalcon\Tag;
use App\Models\Images;

$elem = [];
if($model->edit){
    $elem = $elements;
}

?>
<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2><?= $crudTitle ?></h2>
</div>

<form method="POST" enctype="multipart/form-data" action="<?= !$model->edit ? '/admin/' . $this->dispatcher->getControllerName() . '/item/' . $id : '/admin/' . $this->dispatcher->getControllerName() . '/edit-item/' . $model->id ?>">


 	<div class="form-group">
 		<?= $model->label('name'); ?>
    	<?= Tag::textField(['name', 'maxlength' => 30, 'class' => 'form-control', 'placeholder' => 'Введите название', 'required' => 'required']); ?>
	</div>

	<div class="form-group">
 		<?= $model->label('alias'); ?>
    	<?= Tag::textField(['alias', 'maxlength' => 30, 'class' => 'form-control', 'placeholder' => 'Введите адрес']); ?>
	</div>

	<div class="form-group">
		<?= $model->label('parent_id'); ?>
		<?= Tag::select(['parent_id', $items,
			"using" => [
    	        "id",
    	        "name"
    	    ],
			"useEmpty"   => true,
    	    "emptyText"  => "Выберите родительский элемент",
    	    "emptyValue" => "",
    	    'class' => 'form-control'
    	]); ?>
    </div>

    <div class="form-group">
		<?= $model->label('type_id'); ?>
		<?= Tag::select(['type_id', $model->getType(),
    	    "useEmpty"   => true,
    	    "emptyText"  => "Выберите тип элемента",
    	    "emptyValue" => "",
    	    'class' => 'form-control type-menu',
            'data-url' => '/admin/' . $this->dispatcher->getControllerName() . '/type/' . $id,
    	]); ?>
	</div>

    <div class="form-group">
        <?= $model->label('item_id'); ?>
        <?= Tag::select(['item_id', $elem,
            "useEmpty"   => true,
            "using" => [
                "id",
                "name"
            ],
            "emptyText"  => "Выберите элемент",
            "emptyValue" => "",
            'class' => 'form-control type-menu-option'
        ]); ?>
    </div>

    <div class="form-group">
		<?= $model->label('active'); ?>
		<?= Tag::select(['active', [0 => 'Нет', 1 => 'Да'],
    	    'class' => 'form-control'
    	]); ?>
    </div>

    <div class="form-group">
	    <?= $model->label('position'); ?>
	    <?= Tag::numericField(['position', 'class' => 'form-control', 'placeholder' => 'Порядковый номер']); ?>
 	</div>

	<button type="submit" class="btn btn-primary">Сохранить</button>

</form>