<?php 
use Phalcon\Tag;
use App\Models\Images;
use TableSort\Sort;
use App\Models\MenuItems;

function displayField($field){
  return $field === null || $field === '' ? '<kbd>(Пусто)</kbd>' : $field;
}
$publicDir = $this->getDI()->get('config')->application->backendAssets;
$controller = $this->dispatcher->getControllerName();
?>

<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2><?= $title; ?></h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      	<?= Tag::linkTo(['admin/' . $this->dispatcher->getControllerName() . '/edit-item/' . $model->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
		    <?= Tag::linkTo(['admin/' . $this->dispatcher->getControllerName() . '/delete-item/' . $model->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>

<div class="table-responsive">
<table class="table table-striped table-sm">

  	<tr><td><?= $model->getLabels('id') ?></td><td><?= $model->id; ?></td></tr>

    <tr><td><?= $model->getLabels('name') ?></td><td><?= displayField($model->name) ?></td></tr>

    <tr><td><?= $model->getLabels('alias') ?></td><td><?= displayField($model->alias) ?></td></tr>

	<tr><td><?= $model->getLabels('parent_id') ?></td><td><?= $model->parent_id == 0 ? "Родительская категория" : $model->parent->name ?></td></tr>

	<tr><td><?= $model->getLabels('type_id') ?></td><td><?= $model->getType($model->type_id) ?></td></tr>
	
	<tr><td><?= $model->getLabels('item_id') ?></td><td><?= $item->name ?></td></tr>

	<tr><td><?= $model->getLabels('active') ?></td><td><?= $model->active ? 'Да' : 'Нет' ?></td></tr>
	<tr><td><?= $model->getLabels('position') ?></td><td><?= $model->position ?></td></tr>

	<tr><td><?= $model->getLabels('created_at') ?></td><td><?= displayField($model->created_at) ?></td></tr>

	<tr><td><?= $model->getLabels('updated_at') ?></td><td><?= displayField($model->updated_at) ?></td></tr>

</table>
</div>