<?php 
use Phalcon\Tag;
use App\Models\Images;
use TableSort\Sort;
use App\Models\MenuItems;
function displayField($field){
  return $field === null || $field === '' ? '<kbd>(Пусто)</kbd>' : $field;
}
$publicDir = $this->getDI()->get('config')->application->backendAssets;
$controller = $this->dispatcher->getControllerName();
?>

<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2><?= $title; ?></h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      	<?= Tag::linkTo(['admin/' . $this->dispatcher->getControllerName() . '/edit/' . $model->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
		    <?= Tag::linkTo(['admin/' . $this->dispatcher->getControllerName() . '/delete/' . $model->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>

<div class="table-responsive">
<table class="table table-striped table-sm">

  	<tr><td><?= $model->getLabels('id') ?></td><td><?= $model->id; ?></td></tr>
    <tr><td><?= $model->getLabels('name') ?></td><td><?= displayField($model->name) ?></td></tr>

	<tr><td><?= $model->getLabels('active') ?></td><td><?= $model->active ? 'Да' : 'Нет' ?></td></tr>
	<tr><td><?= $model->getLabels('created_at') ?></td><td><?= displayField($model->created_at) ?></td></tr>
	<tr><td><?= $model->getLabels('updated_at') ?></td><td><?= displayField($model->updated_at) ?></td></tr>

</table>
</div>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2>Элементы меню</h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
        <?= Tag::linkTo(['admin/' . $this->dispatcher->getControllerName() . '/item/' . $model->id, '<i class="fas fa-plus"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>

<div class="table-responsive">
<form action="/admin/<?= $controller ?>/view/<?= $model->id ?>" method="GET">
  <button type="submit" class="btn btn-primary d-none">Поиск</button>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>
          <?= Tag::linkTo(['admin/' . $controller . '/view/' . $model->id . '?' . Sort::sortLink('id'), $itemModel->getLabels('id') . Sort::sortIcon('id')]) ?>
          <input class="form-control" type="number" name="id" min="0" value="<?= $this->request->getQuery("id", "int") ?>">  
        </th>
        <th>
          <?= Tag::linkTo(['admin/' . $controller . '/view/' . $model->id . '?' . Sort::sortLink('name'), $itemModel->getLabels('name') . ' ' . Sort::sortIcon('name')]) ?>
          <input class="form-control" type="text" name="name" value="<?= $this->request->getQuery("name") ?>">
        </th>
        <th>
          <?= Tag::linkTo(['admin/' . $controller . '/view/' . $model->id . '?' . Sort::sortLink('alias'), $itemModel->getLabels('alias') . ' ' . Sort::sortIcon('alias')]) ?>
          <input class="form-control" type="text" name="alias" value="<?= $this->request->getQuery("alias") ?>">
        </th>
        <th>
          <?= Tag::linkTo(['admin/' . $controller . '/view/' . $model->id . '?' . Sort::sortLink('parent_id'), $itemModel->getLabels('parent_id') . ' ' . Sort::sortIcon('parent_id')]) ?>
          <input class="form-control" type="text" name="parent_id" value="<?= $this->request->getQuery("parent_id") ?>">
        </th>
        <th>
          <?= Tag::linkTo(['admin/' . $controller . '/view/' . $model->id . '?' . Sort::sortLink('active'), $itemModel->getLabels('active') . ' ' . Sort::sortIcon('active')]) ?>
          <input class="form-control" type="number" name="active" min="0" value="<?= $this->request->getQuery("active") ?>">
        </th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      <?php $i = 0; foreach ($page->items as $key): ?>
        <tr>
          <td><?= ++$i; ?></td>
          <td><?= $key->id ?></td>
          <td><?= displayField($key->name) ?></td>
          <td><?= displayField($key->alias) ?></td>
          <td><?= $key->parent_id == 0 ? "Родительская категория" : $key->parent->name ?></td>
          <td><?= displayField($key->active) ?></td>
          <td class="btn-group mr-2">
              <?= Tag::linkTo(['admin/' . $controller . '/view-item/' . $key->id, '<i class="far fa-eye"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
              <?= Tag::linkTo(['admin/' . $controller . '/edit-item/' . $key->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
              <?= Tag::linkTo(['admin/' . $controller . '/delete-item/' . $key->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  </form>

  <nav aria-label="Page navigation example">
      <?php $page->items; ?>
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/view/<?= $model->id ?>"><i class="fas fa-angle-double-left"></i></a></li>
      <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/view/<?= $model->id ?>?page=<?= $page->before; ?>"><i class="fas fa-angle-left"></i></a></li>
      <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/view/<?= $model->id ?>?page=<?= $page->next; ?>"><i class="fas fa-angle-right"></i></a></li>
      <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/view/<?= $model->id ?>?page=<?= $page->last; ?>"><i class="fas fa-angle-double-right"></i></a></li>
    </ul>
     <?php echo 'Страница ', $page->current, ' из ', $page->total_pages; ?>
  </nav>


</div>