<?php
use Phalcon\Tag;
use TableSort\Sort;

$controller = $this->dispatcher->getControllerName();

$this->tag->setTitle("Пользователи");
function displayField($field){
  return $field === null ? '<kbd>(Пусто)</kbd>' : $field;
}

?>
<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h2>Пользователи</h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <?= Tag::linkTo(['/admin/' . $controller . '/create', 'Добавить пользователя', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>
      
      <div class="table-responsive">
        <form action="/admin/<?= $controller ?>/index" method="GET">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('id'), $model->getLabels('id') . Sort::sortIcon('id')]) ?>
                <input class="form-control" type="number" name="id" min="0" value="<?= $this->request->getQuery("id", "int") ?>">  
              </th>
              <th>
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('fio'), $model->getLabels('fio') . ' ' . Sort::sortIcon('fio')]) ?>
                <input class="form-control" type="text" name="surname" value="<?= $this->request->getQuery("surname") ?>">
              </th>
              <th class="position-relative">
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('created_at'), $model->getLabels('created_at') . ' ' . Sort::sortIcon('created_at')]) ?>
                <input class="form-control datetimepicker-input" type="text" name="created_at" min="0" value="<?= $this->request->getQuery("created_at") ?>"  autocomplete="off" id="datetimepicker5" data-toggle="datetimepicker" data-target="#datetimepicker5">
              </th>
              <th class="position-relative">
                <?= Tag::linkTo(['admin/' . $controller . '/index?' . Sort::sortLink('updated_at'), $model->getLabels('updated_at') . ' ' . Sort::sortIcon('updated_at')]) ?>
                  <input class="form-control datetimepicker-input" type="text" name="updated_at" min="0" value="<?= $this->request->getQuery("updated_at") ?>" autocomplete="off" data-toggle="datetimepicker" id="datetimepicker6" data-target="#datetimepicker6">
              </th>
              <th>
                <span class="d-block">Действия</span>
                <button type="submit" class="btn btn-primary">Поиск</button>
              </th>
            </tr>
          </thead>
          <tbody>
            <?php $i = 0; foreach ($page->items as $key): ?>
              <tr>
                <td><?= ++$i; ?></td>
                <td><?= $key->id ?></td>
                <td><?php
                  $fio = ''; 
                  if($key->surname){
                    $fio .= $key->surname . ' ';
                  }
                  if($key->name){
                    $fio .= mb_substr($key->name, 0, 1) . '.';
                  }
                  if($key->middlename){
                    $fio .= mb_substr($key->middlename, 0, 1) . '.';
                  }
                  if(empty($fio)){
                    $fio = displayField(null);
                  }
                  echo $fio;
                  ?></td>
                <td><?= displayField($key->created_at) ?></td>
                <td><?= displayField($key->updated_at) ?></td>
                <td class="btn-group mr-2">
                    <?= Tag::linkTo(['admin/' . $controller . '/view/' . $key->id, '<i class="far fa-eye"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                    <?= Tag::linkTo(['admin/' . $controller . '/edit/' . $key->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                    <?= Tag::linkTo(['admin/' . $controller . '/delete/' . $key->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
        </form>


      <nav aria-label="Page navigation example">
          <?php $page->items; ?>
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index"><i class="fas fa-angle-double-left"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->before; ?>"><i class="fas fa-angle-left"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->next; ?>"><i class="fas fa-angle-right"></i></a></li>
          <li class="page-item"><a class="page-link" href="/admin/<?= $controller ?>/index?page=<?= $page->last; ?>"><i class="fas fa-angle-double-right"></i></a></li>
        </ul>
         <?php echo 'Страница ', $page->current, ' из ', $page->total_pages; ?>
      </nav>

      </div>

