<?php 
use Phalcon\Tag;

function displayField($field){
  return $field === null ? '<kbd>(Пусто)</kbd>' : $field;
}
?>

<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2>Пользователь: <?= $user->middlename; ?> <?= $user->name; ?> <?= $user->surname; ?></h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      	<?= Tag::linkTo(['admin/users/edit/' . $user->id, '<i class="fas fa-pencil-alt"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
		<?= Tag::linkTo(['admin/users/delete/' . $user->id, '<i class="fas fa-times"></i>', 'class' => 'btn btn-sm btn-outline-secondary']) ?>
    </div>
  </div>
</div>



<div class="table-responsive">
<table class="table table-striped table-sm">

  	<tr><td><?= $user->getLabels('id') ?></td><td><?= $user->id ?></td></tr>
    <tr><td><?= $user->getLabels('name') ?></td><td><?= displayField($user->name) ?></td></tr>
  	<tr><td><?= $user->getLabels('surname') ?></td><td><?= displayField($user->surname) ?></td></tr>
	<tr><td><?= $user->getLabels('middlename') ?></td><td><?= displayField($user->middlename) ?></td></tr>
	<tr><td><?= $user->getLabels('email') ?></td><td><?= displayField($user->email) ?></td></tr>
	<tr><td><?= $user->getLabels('second_email') ?></td><td><?= displayField($user->second_email) ?></td></tr>
	<tr><td><?= $user->getLabels('phone') ?></td><td><?= displayField($user->phone) ?></td></tr>
	<tr><td><?= $user->getLabels('second_phone') ?></td><td><?= displayField($user->second_phone) ?></td></tr>
	<tr><td><?= $user->getLabels('gender') ?></td><td><?= $user->gender == 0 ? 'Мужской' : 'Женский'?></td></tr>
	<tr><td><?= $user->getLabels('active') ?></td><td><?= $user->active == 1 ? 'Да' : 'Нет' ?></td></tr>
	<tr><td><?= $user->getLabels('banned') ?></td><td><?= $user->banned == 1 ? 'Да' : 'Нет'  ?></td></tr>
	<tr><td><?= $user->getLabels('email_confirmation') ?></td><td><?= $user->email_confirmation == 1 ? 'Да' : 'Нет' ?></td></tr>
	<tr><td><?= $user->getLabels('role_id') ?></td><td><?= $this->acl->roles[$user->role_id] ?></td></tr>
	<tr><td><?= $user->getLabels('created_at') ?></td><td><?= displayField($user->created_at) ?></td></tr>
	<tr><td><?= $user->getLabels('updated_at') ?></td><td><?= displayField($user->updated_at) ?></td></tr>

</table>