<?php
use Phalcon\Tag;
use App\Models\Images;
?>
<?= $this->getContent(); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2><?= $crudTitle ?></h2>
</div>

<form method="POST" enctype="multipart/form-data" action="<?= !$model->edit ? '/admin/' . $this->dispatcher->getControllerName() . '/create' : '/admin/' . $this->dispatcher->getControllerName() . '/edit/' . $model->id ?>">

	<div class="form-group">
		<?= $model->label('post_id'); ?>
		<?= Tag::select(['post_id', $posts,
			"using" => [
    	        "id",
    	        "name"
    	    ],
    	    "useEmpty"   => true,
    	    "emptyText"  => "Выберите запись",
    	    "emptyValue" => "",
    	    'class' => 'form-control'
    	]); ?>
	</div>

	<div class="form-group">
		<?= $model->label('user_id'); ?>
		<?= Tag::select(['user_id', $users,
			"using" => [
    	        "id",
    	        "name"
    	    ],
    	    "useEmpty"   => true,
    	    "emptyText"  => "Выберите автора комментария",
    	    "emptyValue" => "",
    	    'class' => 'form-control'
    	]); ?>
	</div>

	<div class="form-group">
		<?= $model->label('parent_id'); ?>
		<?= Tag::select(['parent_id', $comments,
			"using" => [
    	        "id",
    	        "text"
    	    ],
    	    "useEmpty"   => true,
    	    "emptyText"  => "Выберите родительской комментарий",
    	    "emptyValue" => "",
    	    'class' => 'form-control'
    	]); ?>
	</div>
	
	<div class="form-group">
	    <?= $model->label('text'); ?>
	    <?= Tag::textArea(['text', 'id' => 'editor', 'class' => 'form-control editor', 'placeholder' => 'Введите комментарий']); ?>
 	</div>

    <div class="form-group">
		<?= $model->label('active'); ?>
		<?= Tag::select(['active', [0 => 'Нет', 1 => 'Да'],
    	    'class' => 'form-control'
    	]); ?>
    </div>

	<button type="submit" class="btn btn-primary">Сохранить</button>

</form>